create extension if not exists pgcrypto;
create table if not exists public.products(id bigint primary key,name text not null,category text not null,price numeric(12,2) not null check(price>=0),description text,active boolean not null default true);
create table if not exists public.orders(id uuid primary key default gen_random_uuid(),order_number text unique not null,customer_name text not null,phone text not null,city text not null,address text not null,payment_method text not null,total numeric(12,2) not null,status text not null default 'Pending' check(status in ('Pending','Confirmed','Shipped','Delivered','Cancelled')),created_at timestamptz not null default now());
create table if not exists public.order_items(id bigint generated by default as identity primary key,order_id uuid not null references public.orders(id) on delete cascade,product_id bigint not null references public.products(id),product_name text not null,unit_price numeric(12,2) not null,quantity integer not null check(quantity>0),size text not null default 'S');
insert into public.products(id,name,category,price,description) values
(1,'Noor Lawn Set','Casual',4290,'A soft everyday two-piece with an effortless silhouette.'),(2,'Mehfil Embroidered','Fancy',8990,'Delicate detailing designed for evenings and celebrations.'),(3,'Rang-e-Bahar','Traditional',7490,'A graceful Pakistani-inspired ensemble with timeless charm.'),(4,'Rosé Co-ord','Casual',5190,'Minimal, polished and easy to style throughout the day.'),(5,'Zarqa Festive','Fancy',10990,'Statement festive wear with elegant traditional details.'),(6,'Ivory Kurta','Traditional',3990,'A classic ivory kurta made for simple, beautiful days.'),(7,'Sahar Set','Casual',4590,'Relaxed tailoring with a refined feminine finish.'),(8,'Gulabo Luxe','Fancy',9490,'A romantic festive look for your special moments.'),(9,'Signature Formal','Fancy',150000,'Your featured Aneezay’s statement piece.') on conflict(id) do update set name=excluded.name,category=excluded.category,price=excluded.price,description=excluded.description;
create or replace function public.place_order(p_order_number text,p_customer_name text,p_phone text,p_city text,p_address text,p_payment_method text,p_items jsonb) returns uuid language plpgsql security definer set search_path=public as $$
declare oid uuid; calc numeric:=0; it jsonb; pid bigint; qty int; sz text; pr numeric; nm text;
begin
 if jsonb_array_length(p_items)=0 then raise exception 'Cart is empty'; end if;
 insert into orders(order_number,customer_name,phone,city,address,payment_method,total) values(p_order_number,p_customer_name,p_phone,p_city,p_address,p_payment_method,0) returning id into oid;
 for it in select * from jsonb_array_elements(p_items) loop
  pid=(it->>'product_id')::bigint; qty=(it->>'quantity')::int; sz=coalesce(nullif(it->>'size',''),'S');
  select price,name into pr,nm from products where id=pid and active=true;
  if pr is null or qty<1 then raise exception 'Invalid product or quantity'; end if;
  calc:=calc+(pr*qty);
  insert into order_items(order_id,product_id,product_name,unit_price,quantity,size) values(oid,pid,nm,pr,qty,sz);
 end loop;
 update orders set total=calc where id=oid; return oid;
end;$$;
revoke all on function public.place_order(text,text,text,text,text,text,jsonb) from public;
grant execute on function public.place_order(text,text,text,text,text,text,jsonb) to anon,authenticated;
alter table public.orders enable row level security; alter table public.order_items enable row level security; alter table public.products enable row level security;
create policy "public can read active products" on public.products for select using(active=true);
create policy "owners can read orders" on public.orders for select to authenticated using(true);
create policy "owners can update orders" on public.orders for update to authenticated using(true) with check(true);
create policy "owners can read items" on public.order_items for select to authenticated using(true);
